nyc_parking_violations:
  outputs:
    dev:
      type: duckdb
      path: '../data/nyc_parking_violations.db'
    prod:
      type: duckdb
      # note that path is slightly different here as github actions
      # run from root of repo
      path: './data/prod_nyc_parking_violations.db'
  
  target: dev
